# Generated by Django 3.1.7 on 2021-03-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20210304_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='products/%Y/%d')),
                ('details', models.TextField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.tutorial')),
            ],
        ),
    ]
